import { create } from "zustand";

export const useInfoStore = create((set) => ({
  civilité: "",
  prénom: "",
  nom: "",
  email: "",
  tel: "",
  address: "",
  callType: "",
  label: "",
  siren: null,
  marketing: null,
  profilage: null,
  communication: null,
  done: null,
  sec: "",
  map: "",
  updateCivilité: (civilité) => set(() => ({ civilité: civilité })),
  updatePrénom: (prénom) => set(() => ({ prénom: prénom })),
  updateNom: (nom) => set(() => ({ nom: nom })),
  updateEmail: (email) => set(() => ({ email: email })),
  updateTel: (tel) => set(() => ({ tel: tel })),
  updateAddress: (address) => set(() => ({ address: address })),
  updateCallType: (callType) => set(() => ({ callType: callType })),
  updateSiren: (siren) => set(() => ({ siren: siren })),
  updateMarketing: (marketing) => set(() => ({ marketing: marketing })),
  updateLabel: (label) => set(() => ({ label: label })),
  updateProfilage: (profilage) => set(() => ({ profilage: profilage })),
  updateDone: (done) => set(() => ({ done: done })),
  updateCommunication: (communication) =>
    set(() => ({ communication: communication })),
  setSec: (sec) => set(() => ({ sec: sec })),
  setMap: (map) => set(() => ({ map: map })),
}));
